"""empty message

Revision ID: 23c704abf7da
Revises: 
Create Date: 2019-04-11 00:39:39.681921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c704abf7da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('desc', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domainname', sa.String(length=50), nullable=True),
    sa.Column('desc', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domainname')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=600), nullable=True),
    sa.Column('url', sa.String(length=6000), nullable=True),
    sa.Column('publicationdate', sa.String(length=80), nullable=True),
    sa.Column('content', sa.String(length=12255), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articlecategorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.String(length=250), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['categorie_id'], ['categorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geotag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publishdate', sa.String(length=250), nullable=True),
    sa.Column('content', sa.String(length=250), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geotag')
    op.drop_table('articlecategorie')
    op.drop_table('article')
    op.drop_table('domain')
    op.drop_table('categorie')
    # ### end Alembic commands ###
